set default-list := true

VERSION := `grep -oP '(?<=version = ")[^"]+' typst.toml`
DATA_DIR := if os() == "windows" {
     "%APPDATA%"
} else if os() == "macos" {
    "~/Library/Application\\ Support"
} else {
    "~/.local/share"
}

# Install template to local namespace ($XDG_DATA_HOME)
install-local:
    mkdir -p {{DATA_DIR}}/typst/packages/local/parcio-slides/{{VERSION}}
    cp -r ./* {{DATA_DIR}}/typst/packages/local/parcio-slides/{{VERSION}}

# Create thumbnails for README and thumbnail folder
make-thumbnails: install-local
    typst compile template/slides.typ -f png --pages 1,2,3,4 --ppi 300 thumbnails/p-{0p}.png
    zopflipng -m thumbnails/*.png

bump-version NEW_VERSION:
    @echo Bumping from version {{VERSION}} to {{NEW_VERSION}}
    sed -i "$(printf 's/version = "%s"/version = "%s"/g' "{{VERSION}}" "{{NEW_VERSION}}")" typst.toml
    sed -i "$(printf 's/parcio-slides:%s/parcio-slides:%s/g' "{{VERSION}}" "{{NEW_VERSION}}")" README.md
    find . -iname '*.typ' -exec sed -i "$(printf 's/parcio-slides:%s/parcio-slides:%s/g' "{{VERSION}}" "{{NEW_VERSION}}")" "{}" \;

package: make-thumbnails
    mkdir PACKAGE
    git ls-files | grep -v 'justfile' | while read -r f ; do \
        cp --parents "$f" PACKAGE/ ; \
    done
    cd PACKAGE && \
    find . -iname '*.typ' -exec sed -i 's/@local/@preview/g' "{}" \; && \
    sed -i "$(printf 's+./justfile+https://github.com/parcio/templates/blob/%s/presentation-typst/justfile+g' "$(git rev-parse HEAD)");s+https://parcio.github.io/templates/typst/slides-thumbnails/+thumbnails/+g" README.md && \
    typst-package-check check && \
    tar -czf ../PACKAGE.tar.gz .
    rm -rf PACKAGE
